name: release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: install sbom tool
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-cyclonedx

      - name: generate sbom
        run: |
          (cd /tmp && cargo cyclonedx --manifest-path "$GITHUB_WORKSPACE/Cargo.toml" \
            --format json \
            --override-filename "sbom-${{ github.ref_name }}.cdx")

      - name: upload sbom
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.ref_name }}
          path: "/tmp/sbom-${{ github.ref_name }}.cdx.json"

      - name: publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
